# Generated by Django 6.0.3 on 2026-04-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('hostler', 'Hostler'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
