# Generated by Django 6.0.3 on 2026-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
    ]
