# Generated by Django 6.0.3 on 2026-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_kycdocument_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
