# Generated by Django 6.0.3 on 2026-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_user_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
