# Generated by Django 6.0.3 on 2026-04-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Base_Panel.hostel'),
            preserve_default=False,
        ),
    ]
