from django.urls import path 
from .views import AddHostlerView, AddRoomView, CollectPaymentView, CreateSubscriptionOrderView, DailyMealAssignmentView, Enquery_change_view, EnquiryListView,Edit_hostel, FinancialOverviewView, GenerateUploadURL, HostelFeedbackCreateView, HostelFeedbackListView, HostelListView,AddDocument, HostlerCheckoutView, MealResponsesView, Room_listView, RoomImagesListView, SubscriptionDetailView, VerifySubscriptionPaymentView,my_hostlers,OwnerChatListView,Meal_assignmentView,Owner_Profile,OwnerReplyFeedbackView
urlpatterns = [
    path('add_hostel/', HostelListView.as_view(), name='add_hostel'),
    path("generate-upload-url/", GenerateUploadURL.as_view()),
    path("add-document/", AddDocument.as_view()),
    path("my-hostlers/", my_hostlers.as_view()),
    path('add_hostler/', AddHostlerView.as_view(), name='add_hostler'),
    path("add-room/", AddRoomView.as_view(), name="add_room"),
    path("room-list/", Room_listView.as_view(), name="room_list"),
    path("enquiry-list/", EnquiryListView.as_view(), name="enquiry_list"),
    path("chatrooms/", OwnerChatListView.as_view(), name="owner_chatrooms"),

    path("meal-templates/", Meal_assignmentView.as_view(), name="meal_templates"),
    path("daily-assignments/", DailyMealAssignmentView.as_view(), name="daily_assignments"),
    path("enquery_edit/<int:enquiry_id>/",Enquery_change_view.as_view(),name="enquery_edit" ),
    path("financial-overview/", FinancialOverviewView.as_view(), name="financial_overview"),
    path("image_view/", RoomImagesListView.as_view(), name="image_view"),
    path("edit_hostel/", Edit_hostel.as_view(), name="edit_hostel"),
    path("owner_profile/", Owner_Profile.as_view(), name="owner_profile"),
    path("subscription/create-order/", CreateSubscriptionOrderView.as_view()),
    path("subscription/verify-payment/", VerifySubscriptionPaymentView.as_view()),
    path("subscription/detail/", SubscriptionDetailView.as_view()),
    path("meal-responses/<int:meal_id>/",MealResponsesView.as_view()),
    path("hostels/<int:hostel_id>/feedback/",HostelFeedbackCreateView.as_view()),
    path("hostels/<int:hostel_id>/reviews/",HostelFeedbackListView.as_view()),
    path("feedback/<int:feedback_id>/reply/",OwnerReplyFeedbackView.as_view()),
    path("hostels/checkout_view/",HostlerCheckoutView.as_view()),
    path("collect-payment/",CollectPaymentView.as_view(),name="collect_payment"),
    ]