# Generated by Django 6.0.3 on 2026-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0004_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='hostel',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='hostel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
