# Generated by Django 6.0.3 on 2026-05-02 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0005_remove_chatroom_hostel_chatroom_hostel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='hostel_id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='Base_Panel.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
        migrations.CreateModel(
            name='Hostler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostlers', to='Base_Panel.hostel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostlers', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostlers', to='Base_Panel.room')),
            ],
        ),
    ]
