# Generated by Django 6.0.3 on 2026-05-05 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0007_remove_hostel_image1_remove_hostel_image2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostler',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostler',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hostler',
            name='name',
        ),
        migrations.AddField(
            model_name='hostler',
            name='parent_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hostler',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hostler_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostler',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_hostlers', to=settings.AUTH_USER_MODEL),
        ),
    ]
