# Generated by Django 6.0.3 on 2026-05-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0008_remove_hostler_created_at_remove_hostler_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimage',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Base_Panel.room'),
            preserve_default=False,
        ),
    ]
