# Generated by Django 6.0.3 on 2026-05-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0009_remove_hostelimage_hostel_hostelimage_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_members',
        ),
    ]
