# Generated by Django 6.0.3 on 2026-05-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0010_remove_room_room_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelImage',
            new_name='Room_image',
        ),
    ]
