# Generated by Django 6.0.3 on 2026-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0011_rename_hostelimage_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
