# Generated by Django 6.0.3 on 2026-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0012_hostel_image1_hostel_image2_hostel_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_space',
            field=models.IntegerField(default=1),
        ),
    ]
