# Generated by Django 6.0.3 on 2026-05-08 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0013_room_bed_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_meal_type', models.CharField(choices=[('BRK', 'Breakfast'), ('LNC', 'Lunch'), ('DIN', 'Dinner')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='mess_service',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssignedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BRK', 'Breakfast'), ('LNC', 'Lunch'), ('DIN', 'Dinner')], max_length=3)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_meals', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Panel.hostel')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_meals', to=settings.AUTH_USER_MODEL)),
                ('meal_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base_Panel.mealtemplate')),
            ],
        ),
    ]
