# Generated by Django 6.0.3 on 2026-05-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0014_mealtemplate_hostel_mess_service_assignedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal_templates', to='Base_Panel.hostel'),
            preserve_default=False,
        ),
    ]
