# Generated by Django 6.0.3 on 2026-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0015_mealtemplate_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealtemplate',
            old_name='owner',
            new_name='hostel',
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
