# Generated by Django 6.0.3 on 2026-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0017_hostler_monthly_rent_payment_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_view',
        ),
    ]
