# Generated by Django 6.0.3 on 2026-05-10 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0018_delete_payment_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostler',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
