# Generated by Django 6.0.3 on 2026-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0020_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_image',
            name='image',
            field=models.ImageField(upload_to='Rooms/'),
        ),
    ]
