# Generated by Django 6.0.3 on 2026-05-12 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0021_alter_room_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedmeal',
            options={'ordering': ['-date', 'meal_type']},
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='amount_per_hostler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='meal_image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='assignedmeal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignedmeal',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_meals', to='Base_Panel.hostel'),
        ),
        migrations.AlterField(
            model_name='assignedmeal',
            name='meal_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meals', to='Base_Panel.mealtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedmeal',
            unique_together={('hostel', 'date', 'meal_type')},
        ),
        migrations.CreateModel(
            name='MessCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BRK', 'Breakfast'), ('LNC', 'Lunch'), ('DIN', 'Dinner')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='Base_Panel.assignedmeal')),
                ('hostler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_charges', to='Base_Panel.hostler')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('hostler', 'assigned_meal')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyMessBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_mess_bills', to='Base_Panel.hostler')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('hostler', 'month', 'year')},
            },
        ),
    ]
