# Generated by Django 6.0.3 on 2026-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0025_transaction_created_at_transaction_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedmeal',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
