# Generated by Django 6.0.3 on 2026-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0026_assignedmeal_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcharge',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messcharge',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messcharge',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messcharge',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
