# Generated by Django 6.0.3 on 2026-05-26 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0028_hostelfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedHostler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('hostler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostler_blacklisted', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_blacklist', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base_Panel.room')),
            ],
            options={
                'unique_together': {('owner', 'hostler')},
            },
        ),
    ]
