# Generated by Django 6.0.3 on 2026-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0029_blacklistedhostler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Monthly Rent'), ('mess', 'Mess Fee'), ('cash', 'Cash'), ('full', 'Full Payment')], default='rent', max_length=50),
        ),
    ]
