# Generated by Django 6.0.3 on 2026-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0031_transaction_collected_by_transaction_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='daily_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='days_stayed',
            field=models.IntegerField(default=0),
        ),
    ]
