# Generated by Django 6.0.3 on 2026-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0032_transaction_daily_rent_transaction_days_stayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
