# Generated by Django 6.0.3 on 2026-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0033_transaction_check_out_date_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='daily_rent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='days_stayed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
