# Generated by Django 6.0.3 on 2026-04-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_kycdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='property_proof',
        ),
    ]
