# Generated by Django 6.0.3 on 2026-04-29 04:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_kycdocument_property_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
