# Generated by Django 6.0.3 on 2026-05-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Panel', '0025_transaction_created_at_transaction_owner_and_more'),
        ('Hostlers_panel', '0002_roomchatgroup_roomchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('WANT', 'Want'), ('NOT_WANT', 'Not Want')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assigned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Base_Panel.assignedmeal')),
                ('hostler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_responses', to='Base_Panel.hostler')),
            ],
            options={
                'unique_together': {('assigned_meal', 'hostler')},
            },
        ),
    ]
