services:
  owner_service:
    build: .
    container_name: owner_service
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - stayease_network

  db:
    image: postgres:15
    container_name: owner_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - owner_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stayease_network

  redis:
    image: redis:7
    container_name: owner_redis
    ports:
      - "6380:6379"
    networks:
      - stayease_network

volumes:
  owner_postgres_data:

networks:
  stayease_network:
    external: true    
