# Generated by Django 6.0.3 on 2026-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='stay_days',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='stay_months',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
