# Generated by Django 6.0.3 on 2026-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_panel', '0002_remove_enquiry_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
