# Generated by Django 6.0.3 on 2026-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_panel', '0005_remove_hostelmessage_hostel_hostelmessage_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('closed', 'Closed'), ('accepted by owner', 'Accepted by Owner')], default='pending', max_length=20),
        ),
    ]
