# Generated by Django 6.0.3 on 2026-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_panel', '0006_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
