# Generated by Django 6.0.3 on 2026-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_panel', '0003_enquiry_preferred_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='stay_months',
            field=models.IntegerField(default=1),
        ),
    ]
