services:

  ai_service:
    build: .
    container_name: ai_service

    command: python manage.py runserver 0.0.0.0:8001

    env_file:
      - .env

    ports:
      - "8002:8001"

    volumes:
      - .:/app

    networks:
      - stayease_network

networks:
  stayease_network:
    external: true